version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      target-branch: "elysia"
      schedule:
          interval: daily

    - package-ecosystem: gomod
      directory: "/"
      target-branch: "elysia"
      schedule:
          interval: daily
