---
- - :permit
  - MIT
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 09:56:38.053348539 Z
- - :permit
  - New BSD
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 09:57:07.573740995 Z
- - :permit
  - Simplified BSD
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 09:58:05.917258477 Z
- - :permit
  - ISC
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 09:59:13.166183153 Z
- - :permit
  - Apache 2.0
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 10:58:32.979628836 Z
- - :permit
  - BSD Zero Clause License
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 10:59:28.428874456 Z
- - :permit
  - CC0-1.0
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 11:04:46.084003007 Z
- - :permit
  - CC-BY-4.0
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 11:05:21.140663822 Z
- - :permit
  - Python-2.0
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 11:06:06.340901831 Z
- - :permit
  - Unlicense
  - :who:
    :why:
    :versions: []
    :when: 2024-01-22 11:06:21.707810263 Z
- - :permit
  - BlueOak-1.0.0
  - :who:
    :why:
    :versions: []
    :when: 2024-07-22 13:18:24.964294000 Z
- - :permit
  - SIL OPEN FONT LICENSE Version 1.1
  - :who:
    :why:
    :versions: []
    :when: 2024-07-22 13:23:28.733595000 Z
- - :permit
  - Mozilla Public License 2.0
  - :who:
    :why:
    :versions: []
    :when: 2024-10-18 10:53:36.342945000 Z
- - :approve
  - valid-url
  - :who:
    :why:
    :versions: []
    :when: 2025-01-04 10:01:40.975889000 Z
- - :permit
  - BSD
  - :who:
    :why:
    :versions: []
    :when: 2025-01-04 10:02:50.460763000 Z
- - :permit
  - public domain
  - :who:
    :why:
    :versions: []
    :when: 2025-01-04 10:03:06.513618000 Z
