name: ESLint check
on: [push, pull_request]

jobs:
    eslint:
        name: ESLint test
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn install
            - name: Check with ESLint
              run: yarn ci:lint
