name: Vitest CI
permissions: {}
on:
    pull_request:
        types:
            - opened
            - synchronize
    push:
        branches:
            - "**"

jobs:
    eslint:
        name: Test with Vitest
        runs-on: ubuntu-latest
        permissions:
            contents: read

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Enable corepack
              run: corepack enable

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: pnpm install

            - name: Execute vitest
              run: pnpm ci:vitest
